---
title: "Twitter Sentiment Analysis"
output: Sentiment graph, word cloud
---

Import libraries

```{r}
library("NLP")
library("twitteR")
library("syuzhet")
library("tm")
library("SnowballC")
library("stringi")
library("ROAuth")
library("base64enc")
library("tm")
library("ggplot2")
library("wordcloud")
```

Twitter Access Authentication

```{r}
consumer_key <- ''
consumer_secret <- ''
access_token <- ''
access_secret <- ''
setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
```

Fetch tweets

```{r}
tweets <- searchTwitter("#", n=1000,lang = "en")

DF_tweets <- twListToDF(tweets)
```

Preprocess fetched data

```{r}
tweets_text<- DF_tweets$text

#convert all text to lower case
tweets_text<- tolower(tweets_text)

# Replace blank space (“rt”)
tweets_text <- gsub("rt", "", tweets_text)

# Replace @UserName
tweets_text <- gsub("@\\w+", "", tweets_text)

# Remove punctuation
tweets_text <- gsub("[[:punct:]]", "", tweets_text)

# Remove links
tweets_text <- gsub("http\\w+", "", tweets_text)

# Remove tabs
tweets_text <- gsub("[ |\t]{2,}", "", tweets_text)

# Remove blank spaces at the beginning
tweets_text <- gsub("^ ", "", tweets_text)

# Remove blank spaces at the end
tweets_text <- gsub(" $", "", tweets_text)

#create corpus
DF_tweets.text.corpus <- Corpus(VectorSource(tweets_text))
```

Remove stopwords from tweets

```{r}
#clean up by removing stop words
DF_tweets.text.corpus <- tm_map(DF_tweets.text.corpus, function(x)removeWords(x,stopwords()))
```

Generate wordcloud

```{r}
#generate wordcloud
wordcloud(DF_tweets.text.corpus,min.freq = 10,colors=brewer.pal(8, "Dark2"),random.color = TRUE,max.words = 500)
```

Generate sentiment graph

```{r}
#getting emotions using in-built function
mysentiment_tweets<-get_nrc_sentiment((tweets_text))

#calculationg total score for each sentiment
Sentimentscores_tweets<-data.frame(colSums(mysentiment_tweets[,]))

names(Sentimentscores_tweets)<-"Score"
Sentimentscores_tweets<-cbind("sentiment"=rownames(Sentimentscores_tweets),Sentimentscores_tweets)
rownames(Sentimentscores_tweets)<-NULL


#plotting the sentiments with scores
ggplot(data=Sentimentscores_tweets,aes(x=sentiment,y=Score))+geom_bar(aes(fill=sentiment),stat = "identity")+
  theme(legend.position="none")+
  xlab("Sentiments")+ylab("scores")+ggtitle("Sentiments of people behind the choosen topic")
```
